### ISSUE TITLE
初心者がMVT作成にトライしてみた。

### ISSUE THREAD

**Issue by wata909** [hfu/tomogala#19]
### きっかけ
いろいろあって、MVTを作りたくなった。初めてやる人向けに参考になるかなということで、ざっくりとですが、まとめました。なぜ作りたくなったのかは、機会があれば紹介します。

### やってみて上手くいかなかった
まず、検索した。
で、出てきたサイトの内、[バイナリベクトルタイルの作り方 – GUNMA GIS GEEK - shimizu](https://shimz.me/blog/leaflet-js/5354)を参考させていただいた。
GUNMA GIS GEEKさんでは、[tippecanoe](https://github.com/mapbox/tippecanoe)と[mbutil](https://github.com/mapbox/mbutil)を使ってられたが、[ogr2ogr](https://www.gdal.org/ogr2ogr.html)でも、[MVTに対応している](https://www.gdal.org/drv_mvt.html)ようなので、手を抜くためにそちらを使おうともくろむ。素直に、

```
ogr2ogr -f MVT mytileset source.gpkg -dsco MAXZOOM=10
```

みたいな感じでタイルを作成し、GUNMA GIS GEEKさんのサンプルを使って表示し見てる。表示されない :-(

ogr2ogrの問題なのかと思い、[バイナリベクトルタイルをQGISで表示する - 自然環境保全のための周辺技術](http://tmizu23.hatenablog.com/entry/20171209/1512787590)を参考にして、Windows環境にBash on Ubuntu on Windows（正確にはUbuntuを入れました）と、tippecanoeを導入、これまた素直に

```
tippecanoe -e veg veg.geojson
```

みたいな感じで、pbfファイルを生成、サンプルに表示させようとした。・・・やっぱり表示されない :-(

### と、いうことで、聞いてみた。
ということで、[FB上で質問してみた](https://www.facebook.com/100001506916479/posts/1893976493995896/?comment_id=1895111440549068)。その結果、

- 生成されたpbfファイルがqzip圧縮されている
- sampleのコードにフィルタが設定されていて、元のレイヤ名が指定されていて、そのままでは表示されない

との指摘があった。ということで、

```
cd ./tiles
gzip -d -v -r -S .pbf *
find . -type f -exec mv -v '{}' '{}'.pbf \;
```
としてpbfファイルを解凍し、 filterをコメントアウトしたら表示された。成果物は、[こちら](https://wata909.github.io/mvt_test/#13/43.0616/141.3575)。

### 応用例
今回表示されなかったのは、pbfファイルがqzip圧縮されていたことが原因だったが、これは、tippecanoeで非圧縮というオプションがあった。これを指定すれば上手くいくのかどうか、確認したかったが、 @koukita 氏が[北海道胆振東部地震 厚真川地区 正射画像の崩落地形についてトレースしたデータを公開さた](https://github.com/koukita/2018_09_06_atumatyou)ので、これで試してみることとした。

```
tippecanoe -e tiles -pC -z19 atsuma20180909.geojson
```

でタイルを生成したところ、問題なく表示された。できたものは[こちら](https://wata909.github.io/atsuma_mvt/#16/42.7503/141.9141)。

### 残った宿題

- 実は、本当に変換したいデータは、結構重たかったりする。広域を表示するときにはちょっと重いかなーと思うので、簡素化について検討したい
- gzip圧縮で表示されないのは、leaflet0.7+pluginの環境だからだろうか。サイズ的には圧縮されていた方がいいのは当然なので、他のクライアントも要検討。
- あとそういえば、[自分のデータもあったなー](https://github.com/wata909/habs_test)と。こいつもバイナリベクタにして、全体を表示したいかな。でも、そうすると属性にもとづく色づけをしないと。
- ogr2ogr にも非圧縮のオプションがあるので、それでも大丈夫なのか、要確認。

**Comment by hfu** [comment]
ありがとうございます！実際にやってみられた観点から「ベクトルタイル生産、こうあってほしい」という理想があったら教えていただけるとありがたいです。

ちなみに、「残った宿題」への純技術的な反応は次の通りになる気がします。

## 「残った宿題」への純技術的な反応
- 簡素化を手軽かつしっかりできるのは tippecanoe です。Windows 環境で tippecanoe を使うことが難しいことは承知しているのですが、tippecanoe を最初から使う、というのが本来の正解である気がします。
- gzip 圧縮で表示されないのは、クライアントのせいではなくてサーバのせいです。本来、gzip 圧縮は通信路の問題なので、サーバが「これは圧縮されているよ」と言って、ブラウザが「承知。展開してアプリに渡す。」と反応するのが本来の姿です。ライブラリに圧縮したデータが渡される、という状態になるのは本来の姿ではなく、本来の姿を実現しなかった犯人はサーバ、つまりこの場合は gh-pages です。とはいえ、gh-pages にそれを認識させるのは酷なので、国連ベクトルタイルツールキットでは [tile-block](https://github.com/hfu/tile-block) を備えています。
- 属性に基づく色付けをしたい時、オープンソースで手軽にできるソリューションは maputnik だと思います。mbtiles から maputnik につなぐ部分があまり自動化されていないところに、ベクトルタイル生産の円滑化の課題がありそうですね。
- ogr2ogr と tippecanoe で、選ぶ環境にあまり差がない場合には、tippecanoe に資源を集中する方が話が早い気がします。もちろん、卵を複数のバスケットに分散することのメリットはあると思いますが、今は資源を集中するほうが優先するかもしれません。

**Comment by wata909** [comment]
ありがとうございます！！

### こんな情報があったらいいなリスト
ということで、「バイナリベクトルタイル生産」にむけて、こんな説明があるとうれしいなのリストを思いつくまま、列挙してみます。

- **そもそも、なぜバイナリベクトルタイル？**　きっと歴史的には、クエリで画像を返すWebGISがあって、それだと遅くてキャッシュやタイルができて、ラスタじゃ色々できないことがあるからベクタトルタイルができて、ベクタトルタイルだと重いので、バイナリベクトルタイルができた、って流れだと思うのです。私のような長い間そういうのを見ている人間は、バイナリベクトルタイルの必然性が見えるだろうけど、そうじゃない人には、なんでバイナリベクトルタイルなの、というそもそもが見えないかもしれない。その辺の説明がありつつ、自分の必要なアウトプットに対して、必要な技術を選択できるような、ドキュメントがあるといいかもしれない。

- **生産はできるけど、表示ができない。** 自分の場合、ローカル環境で地理空間情報を扱うことが多いので、ファイルを変換する所まではそれなりにできました。が、JavaScriptが全くわからず、そこで結構、躓いた(汗　データを作る人は、データを見たいというのもあるだろうから、その辺のサンプルというか、JavaScriptに書かれている内容の解説が欲しい(汗　フロントエンドがわかる技術者には当たり前のことかもしれませんが、結構、何を見ればいいのかわからんです・・・

- **生産範囲をZ/X/Yで指定したいよね** これは、広範囲になればなるほど、リクエストが出てる気がします。gdal2tilesでは、なーんもないタイルが大量生産された覚えが。MVTの場合、どうなんだろ？

### 「残った宿題」への純技術的な反応に対する、御礼
- ogr2ogrを使ったのは、tippecanoe 環境を整えるのがめんどくさかったのと、shpファイルをGeoJSONに変えるのが面倒だったので、shp→geopakage→MVTと、したかった、ということです。実際は、Windows Subsystem for LinuxでUbuntuを使えるようにすれば、いいだけで、Dockerを入れるよりも簡単でした(いや、本当に簡単。素晴らしく簡単)。元々Ubuntuは別環境で使っているので、そういう人であれば、全然問題ないですね。
- どちらかというと、GeoJSONだと、日本全国、1/2,500クラスのバイナリベクトルタイルを作る、といった話になるとき、サイズ的に不安かも・・・、という話かもしれません。
- gzipは、サーバー周りなのですね。その辺の設定もわからないです・・。あと、そもそも自分の持ってる環境だと、いじれるかどうかも、ちょっと謎です・・・
- 属性に基づく色付けは、自動化するというよりも、まずはhtmlもしくはjsファイルがぐりぐりいじるのかな、と思ってました。それをやったあとに、沢山やるのは面倒でしょ、maputnikがあるよ、という方が、ハンズオン的な技術習得としては、理解しやすいかなと感じます。

**Comment by hfu** [comment]
@wata909 ありがとうございます。いただいたコメントを受けて、下記8件のイシューを立ててみました。これから国連ベクトルタイルツールキットのコミュニティを形成していくにあたって、いいヒントをいただきました。ありがとうございます。

1. [バイナリベクトルタイルの歴史的必然性の説明](https://github.com/hfu/tomogala/issues/20)
2. [必要なベクトルタイルのアウトプットに対して、必要な技術を選択できるようなドキュメント](https://github.com/hfu/tomogala/issues/21)
3. [ベクトルタイル表示サイトに書かれている HTML の内容の解説](https://github.com/hfu/tomogala/issues/22)
4. [生産範囲を指定する方法について](https://github.com/hfu/tomogala/issues/23)
5. [tippecanoe on Windows](https://github.com/hfu/tomogala/issues/24)
6. [ベクトルタイル生産に GeoJSON を介すことへのサイズ不安の解消](https://github.com/hfu/tomogala/issues/25)
7. [ベクトルタイルの gzip 圧縮まわりの理解と対策](https://github.com/hfu/tomogala/issues/26)
8. [Styling をハンズオンで伝える方法](https://github.com/hfu/tomogala/issues/27)
