### ISSUE TITLE
tippecanoe on Windows

### ISSUE THREAD

**Issue by hfu** [hfu/tomogala#24]
#19 からのスピンオフです。

> Windows Subsystem for Linux で ubuntu を使えるようにすればいい。Docker を入れるよりも簡単である。

とのことですから、これをなぞっておくのが良いと思います。

**Comment by hfu** [comment]
まず手始めに、私の家には Windows 10 Professional の環境がないので、これを手に入れるべきか迷っています。外付けの HDD は使うとして、300ドル以下の Windows 10 Professional PC として [Inspiron](https://www.dell.com/en-us/work/shop/dell-laptops-and-notebooks/inspiron-11-3000/spd/inspiron-11-3180-laptop/smi113w10h1c3007p?view=configurations&selectionState=eyJGUHJpY2UiOjI4OS45OSwiSVVQcmljZSI6Mjg5Ljk5LCJPQyI6InNtaTExM3cxMGgxYzMwMDdwIiwiUXR5IjoxLCJQclN0IjoiIiwiTW9kcyI6W3siSWQiOjU3MiwiT3B0cyI6W3siSWQiOiJGRzAwMDUifV19LHsiSWQiOjExLCJPcHRzIjpbeyJJZCI6IkUxMFA2NEUifV19XX0%253D) みたいなものを手に入れてみようかと思っていますが、ご助言あればいただけるとありがたいです。

**Comment by wata909** [comment]
自分の環境ですと、HP SPECTRE X360で、メモリやらHDDやらは沢山あるのですがWindwosは10 Homeです。なので、HomeはあるけどProがないということであれば、Home環境のままでOKです。その祖もWinのPCがないということであれば、Insrironとか、いいかもですね。あと日本国内では中古のPCという手もあるのですが、そちらではいかがでしょう（汗

**Comment by hfu** [comment]
ありがとうございます！Windows 10 Home でも動くのですね！貴重な情報、ありがとうございます。
別個のチャンネルで議論してみまして、まずは従量制仮想機械サービスのほうを優先的に探ってみようとも思い始めています。なにかチャンスを見つけることがあったら、Windows Subsystem for Linux で ubuntu で tippecanoe、というのをぜひ試してみたいと思っています。

**Comment by hfu** [comment]
その後、状況が進みまして、HP Stream 11 Pro G4 EE Notebook PC (2UL97UT) を私費購入してみることにしました。200 ドル PC でもベクトルタイルできることを示してみようと思っています。

**Comment by hfu** [comment]
HP Stream 11 が手に入ったので、tippecanoe を動かすところまで持っていきました。備忘のため、作業の内容を書いておくと、次のとおりでした。

## Windows システム更新・調整関係
1. Windows Update と、ディスク領域の確保も兼ねての不要なソフトウェアの削除
2. BIOS レベルでの Hyper-V の enable
3. Windows の機能における Hyper-V と Windows Subsystem for Linux の有効化
4. Store からの Ubuntu のインストール

## Ubuntu 内部での調整関係
1. sudo apt-get update
2. sudo apt-get upgrade
3. sudo apt-get install gcc
4. git config --global user.name "Hidenori Fujimura"
5. git config --global user.email "hfu@users.noreply.github.com"
6. (git/github のための SSH 秘密鍵の準備)
7. git clone git@github.com:mapbox/tippecanoe
8. cd tippecanoe
9. sudo apt-get install make
10. sudo apt-get install g++
11. sudo apt-get install build-essential libsqlite3-dev zlib1g-dev
12. make -j
13. sudo make install

これで、次のとおりの出力が得られるところまでいきました。

```console
$ tippecanoe -v
tippecanoe v1.31.7
```
